### ISSUE TITLE
Defferal Problem

### ISSUE THREAD

**Issue by LQGundi** [SecondSonConsulting/swiftDialogExamples#2]
Hello everyone, I tried my hand at the defferall script. Unfortunately Jamf recognizes both buttons. If I select defferal or now update the following script starts. Do you have any idea how I could adjust this?

**Comment by BigMacAdmin** [comment]
Need more information than this. When you say "The following script starts" are you implying that you have a single jamf policy with multiple scripts?

Basic recommendation would be:
1) Do everything inside the deferral script
or 
2) Have the deferral script call another policy via custom event when the user chooses to do the thing
