### ISSUE TITLE
default notification icon

### ISSUE THREAD

**Issue by mltsalg** [SecondSonConsulting/swiftDialogExamples#3]
<img width="370" alt="Screenshot logo" src="https://github.com/SecondSonConsulting/swiftDialogExamples/assets/135068922/e9571453-6dd1-4089-af61-1f3806622e6f">

I've replaced the company default logo with mine (1024x1024 also 512x512) but it still shows a very tiny and old logo post attempts to change it a completely different logo of the same size. My log and script below.. Where did I go wrong?

```
#!/bin/bash

png_file="/Users/Shared/Jamf.png" 
temp_file=$(/usr/bin/mktemp)
dialogDir="/Library/Application Support/Dialog"


/bin/cp "$png_file" "$temp_file"
sleep 2

sudo /bin/mkdir -p "$dialogDir"
sleep 2

sudo /usr/bin/sips -s format png "$temp_file" --out "$dialogDir"/Dialog.png
sleep 2
```
============

[2024-01-26 00:39:36] swiftDialog postinstall started
[2024-01-26 00:39:37] swiftDialog 2.3.3.4734
[2024-01-26 00:39:37] Icon file detected. Updating dialog icon
Custom icon assigned to folder '/Library/Application Support/Dialog/Dialog.app' based on '/Library/Application Support/Dialog/Dialog.png'.
[2024-01-26 00:39:37] Icon update success
[2024-01-26 00:39:37] Checking for Setup Assistant
[2024-01-26 00:39:38] Current user is username
[2024-01-26 00:39:38] swiftDialog postinstall complete

**Comment by BigMacAdmin** [comment]
Sorry, but this is not relevant to this github repo.

You'll want to ask questions on the Mac Admins Slack #swiftdialog channel, or post this issue on the official SwiftDialog repo: https://github.com/swiftDialog/swiftDialog
